// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/redis/kuji_store.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/redis/kuji_store.go -destination=internal/repository/redis/mock/kuji_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/brucechen520/kuji-go/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockKujiStore is a mock of KujiStore interface.
type MockKujiStore struct {
	ctrl     *gomock.Controller
	recorder *MockKujiStoreMockRecorder
	isgomock struct{}
}

// MockKujiStoreMockRecorder is the mock recorder for MockKujiStore.
type MockKujiStoreMockRecorder struct {
	mock *MockKujiStore
}

// NewMockKujiStore creates a new mock instance.
func NewMockKujiStore(ctrl *gomock.Controller) *MockKujiStore {
	mock := &MockKujiStore{ctrl: ctrl}
	mock.recorder = &MockKujiStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKujiStore) EXPECT() *MockKujiStoreMockRecorder {
	return m.recorder
}

// GetBoxInventory mocks base method.
func (m *MockKujiStore) GetBoxInventory(ctx context.Context, boxID uint) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoxInventory", ctx, boxID)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoxInventory indicates an expected call of GetBoxInventory.
func (mr *MockKujiStoreMockRecorder) GetBoxInventory(ctx, boxID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoxInventory", reflect.TypeOf((*MockKujiStore)(nil).GetBoxInventory), ctx, boxID)
}

// GetSeriesMeta mocks base method.
func (m *MockKujiStore) GetSeriesMeta(ctx context.Context, seriesID uint) (*model.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeriesMeta", ctx, seriesID)
	ret0, _ := ret[0].(*model.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeriesMeta indicates an expected call of GetSeriesMeta.
func (mr *MockKujiStoreMockRecorder) GetSeriesMeta(ctx, seriesID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeriesMeta", reflect.TypeOf((*MockKujiStore)(nil).GetSeriesMeta), ctx, seriesID)
}

// SetBoxInventory mocks base method.
func (m *MockKujiStore) SetBoxInventory(ctx context.Context, boxID uint, inv map[string]int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBoxInventory", ctx, boxID, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBoxInventory indicates an expected call of SetBoxInventory.
func (mr *MockKujiStoreMockRecorder) SetBoxInventory(ctx, boxID, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBoxInventory", reflect.TypeOf((*MockKujiStore)(nil).SetBoxInventory), ctx, boxID, inv)
}

// SetSeriesMeta mocks base method.
func (m *MockKujiStore) SetSeriesMeta(ctx context.Context, seriesID uint, series *model.Series) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSeriesMeta", ctx, seriesID, series)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSeriesMeta indicates an expected call of SetSeriesMeta.
func (mr *MockKujiStoreMockRecorder) SetSeriesMeta(ctx, seriesID, series any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSeriesMeta", reflect.TypeOf((*MockKujiStore)(nil).SetSeriesMeta), ctx, seriesID, series)
}
