// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/postgre/client/series_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/postgre/client/series_repo.go -destination=internal/repository/postgre/client/mock/series_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/brucechen520/kuji-go/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSeriesRepository is a mock of SeriesRepository interface.
type MockSeriesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeriesRepositoryMockRecorder
	isgomock struct{}
}

// MockSeriesRepositoryMockRecorder is the mock recorder for MockSeriesRepository.
type MockSeriesRepositoryMockRecorder struct {
	mock *MockSeriesRepository
}

// NewMockSeriesRepository creates a new mock instance.
func NewMockSeriesRepository(ctrl *gomock.Controller) *MockSeriesRepository {
	mock := &MockSeriesRepository{ctrl: ctrl}
	mock.recorder = &MockSeriesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeriesRepository) EXPECT() *MockSeriesRepositoryMockRecorder {
	return m.recorder
}

// GetBoxInventoryById mocks base method.
func (m *MockSeriesRepository) GetBoxInventoryById(ctx context.Context, id uint) ([]model.Prize, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoxInventoryById", ctx, id)
	ret0, _ := ret[0].([]model.Prize)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoxInventoryById indicates an expected call of GetBoxInventoryById.
func (mr *MockSeriesRepositoryMockRecorder) GetBoxInventoryById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoxInventoryById", reflect.TypeOf((*MockSeriesRepository)(nil).GetBoxInventoryById), ctx, id)
}

// GetSeriesById mocks base method.
func (m *MockSeriesRepository) GetSeriesById(ctx context.Context, id uint) (*model.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeriesById", ctx, id)
	ret0, _ := ret[0].(*model.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeriesById indicates an expected call of GetSeriesById.
func (mr *MockSeriesRepositoryMockRecorder) GetSeriesById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeriesById", reflect.TypeOf((*MockSeriesRepository)(nil).GetSeriesById), ctx, id)
}
