package code

var zhTWText = map[int]string{
	ServerError:        "內部伺服器錯誤",
	TooManyRequests:    "請求過於頻繁",
	ParamBindError:     "參數資訊錯誤",
	AuthorizationError: "簽名資訊錯誤",
	UrlSignError:       "參數簽名錯誤",
	CacheSetError:      "設置快取失敗",
	CacheGetError:      "獲取快取失敗",
	CacheDelError:      "刪除快取失敗",
	CacheNotExist:      "快取不存在",
	ResubmitError:      "請勿重複提交",
	HashIdsEncodeError: "HashID 加密失敗",
	HashIdsDecodeError: "HashID 解密失敗",
	RBACError:          "暫無存取權限",
	RedisConnectError:  "Redis 連線失敗",
	MySQLConnectError:  "MySQL 連線失敗",
	WriteConfigError:   "寫入設定檔失敗",
	SendEmailError:     "發送郵件失敗",
	MySQLExecError:     "SQL 執行失敗",
	GoVersionError:     "Go 版本不符合要求",
	SocketConnectError: "Socket 未連線",
	SocketSendError:    "Socket 訊息發送失敗",

	AuthorizedCreateError:    "創建呼叫方失敗",
	AuthorizedListError:      "獲取呼叫方列表失敗",
	AuthorizedDeleteError:    "刪除呼叫方失敗",
	AuthorizedUpdateError:    "更新呼叫方失敗",
	AuthorizedDetailError:    "獲取呼叫方詳情失敗",
	AuthorizedCreateAPIError: "創建呼叫方 API 地址失敗",
	AuthorizedListAPIError:   "獲取呼叫方 API 地址列表失敗",
	AuthorizedDeleteAPIError: "刪除呼叫方 API 地址失敗",

	AdminCreateError:             "創建管理員失敗",
	AdminListError:               "獲取管理員列表失敗",
	AdminDeleteError:             "刪除管理員失敗",
	AdminUpdateError:             "更新管理員失敗",
	AdminResetPasswordError:      "重置密碼失敗",
	AdminLoginError:              "登入失敗",
	AdminLogOutError:             "登出失敗",
	AdminModifyPasswordError:     "修改密碼失敗",
	AdminModifyPersonalInfoError: "修改個人資訊失敗",
	AdminMenuListError:           "獲取管理員選單授權列表失敗",
	AdminMenuCreateError:         "管理員選單授權失敗",
	AdminOfflineError:            "下線管理員失敗",
	AdminDetailError:             "獲取個人資訊失敗",

	MenuCreateError:       "創建選單失敗",
	MenuUpdateError:       "更新選單失敗",
	MenuDeleteError:       "刪除選單失敗",
	MenuListError:         "獲取選單列表失敗",
	MenuDetailError:       "獲取選單詳情失敗",
	MenuCreateActionError: "創建選單欄功能權限失敗",
	MenuListActionError:   "獲取選單欄功能權限列表失敗",
	MenuDeleteActionError: "刪除選單欄功能權限失敗",

	CronCreateError:  "創建後台任務失敗",
	CronUpdateError:  "更新後台任務失敗",
	CronListError:    "獲取定時任務列表失敗",
	CronDetailError:  "獲取定時任務詳情失敗",
	CronExecuteError: "手動執行定時任務失敗",
}
