// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/brucechen520/kuji-go/internal/config"
	client3 "github.com/brucechen520/kuji-go/internal/handler/client"
	"github.com/brucechen520/kuji-go/internal/pkg"
	"github.com/brucechen520/kuji-go/internal/repository/postgre/client"
	"github.com/brucechen520/kuji-go/internal/repository/redis"
	"github.com/brucechen520/kuji-go/internal/route"
	client2 "github.com/brucechen520/kuji-go/internal/service/client"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*gin.Engine, func(), error) {
	db, cleanup, err := pkg.InitDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	userRepository := client.NewUserRepo(db)
	redisClient, cleanup2, err := pkg.InitRedis(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tokenStore := redis.NewTokenStore(redisClient)
	authConfig := &cfg.Auth
	authService := client2.NewAuthService(userRepository, tokenStore, authConfig)
	authHandler := client3.NewAuthHandler(authService)
	seriesRepository := client.NewSeriesRepo(db)
	kujiStore := redis.NewKujiStore(redisClient)
	seriesService := client2.NewSeriesService(seriesRepository, kujiStore, authConfig)
	seriesHandler := client3.NewSeriesHandler(seriesService)
	handlerGroup := route.NewHandlerGroup(authHandler, seriesHandler)
	engine := route.NewRouter(handlerGroup)
	return engine, func() {
		cleanup2()
		cleanup()
	}, nil
}
