// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/brucechen520/kuji-go/internal/config"
	client2 "github.com/brucechen520/kuji-go/internal/handler/client"
	"github.com/brucechen520/kuji-go/internal/repository"
	"github.com/brucechen520/kuji-go/internal/repository/postgre"
	"github.com/brucechen520/kuji-go/internal/repository/redis"
	"github.com/brucechen520/kuji-go/internal/route"
	"github.com/brucechen520/kuji-go/internal/service/client"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*gin.Engine, func(), error) {
	db, err := repository.InitDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	userRepository := postgre.NewUserRepo(db)
	redisClient, err := repository.InitRedis(cfg)
	if err != nil {
		return nil, nil, err
	}
	tokenStore := redis.NewTokenStore(redisClient)
	authConfig := &cfg.Auth
	authService := client.NewAuthService(userRepository, tokenStore, authConfig)
	authHandler := client2.NewAuthHandler(authService)
	engine := route.NewRouter(authHandler)
	return engine, func() {
	}, nil
}
